--crear tabla usuarios para el ingreso de la api
CREATE TABLE usuario (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CONTRASENA TEXT NOT NULL
);
--crear tabla ROL PARA CONTROLAR EL ACCESO A LA APP
CREATE TABLE ROL (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) UNIQUE NOT NULL
);
--CREAMOS LA TABLA USUARIO_ROL COMO TABLA DE UNION ENTRE USUARIO Y ROL
CREATE TABLE USUARIO_ROL (
    USUARIO_ID INTEGER NOT NULL,
    ROL_ID INTEGER NOT NULL,
    PRIMARY KEY (USUARIO_ID, ROL_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ID)
);

INSERT INTO usuario (nombre, email, contrasena)
VALUES ('admin', 'admin@admin.com', '$2a$10$tU9w0qRhCtLhM/ceJoS5Tesczib8gfG/cveeEWVt2VxGl57JprL');

INSERT INTO rol (nombre) VALUES ('Administrador');
INSERT INTO rol (nombre) VALUES ('Empleado');
SELECT id FROM usuario WHERE email = 'admin@admin.com';
SELECT id FROM rol WHERE nombre = 'Administrador';
INSERT INTO usuario_rol (usuario_id, rol_id)
VALUES (1, 1);

--CREAMOS LA TABLA Empleado 

CREATE TABLE EMPLEADO (
    ID SERIAL PRIMARY KEY,
    FECHA_INGRESO DATE,
    NOMBRE VARCHAR(50) NOT NULL,
    SALARIO NUMERIC(10, 2)
);

