--crear tabla usuarios para el ingreso de la api
CREATE TABLE usuario (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CONTRASENA TEXT NOT NULL
);
--crear tabla ROL PARA CONTROLAR EL ACCESO A LA APP
CREATE TABLE ROL (
    ID SERIAL PRIMARY KEY,
    NOMBRE VAERCHAR(50) UNIQUE NOT NULL
);
--CREAMOS LA TABLA USUARIO_ROL COMO TABLA DE UNION ENTRE USUARIO Y ROL
CREATE TABLE USUARIO_ROL (
    USUARIO_ID INTEGER NOT NULL,
    PRIMARY KEY (USUARIO_ID, ROL_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ID)
);
--CREAMOS LA TABLA Empleado 

CREATE TABLE EMPLEADO (
    ID SERIAL PRIMARY KEY,
    FECHA_INGRESO DATE,
    NOMBRE VARCHAR(50) NOT NULL,
    SALARIO NUMERIC(10, 2)
);


